### ISSUE TITLE
Can't get nowin or kestrel to run the samples on centos 6.5, mono 3.8.0

### ISSUE THREAD

**Issue by andrewaggb** [davidfowl/HelloWorldVNext#10]
as root
yum -y install libuv libuv-devel

as myself
mozroots --import --sync
curl https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.sh | sh
source .kre/kvm/kvm.sh
kvm install 1.0.0-alpha3
git clone https://github.com/aspnet/Home.git
cd Home/samples/HelloMvc
kpm restore
k kestrel
....
/home/andrew/.kre/packages/KRE-mono45-x86.1.0.0-alpha3/bin/klr.host.dll Information : 0 : [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.HeaderValueAbstractions in 0ms
/home/andrew/.kre/packages/KRE-mono45-x86.1.0.0-alpha3/bin/klr.host.dll Information : 0 : [LoaderContainer]: Load name=Microsoft.AspNet.Server.Kestrel
/home/andrew/.kre/packages/KRE-mono45-x86.1.0.0-alpha3/bin/klr.host.dll Information : 0 : [DefaultLoaderEngine]: LoadFile(/home/andrew/.kpm/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-alpha3/lib/net45/Microsoft.AspNet.Server.Kestrel.dll)
/home/andrew/.kre/packages/KRE-mono45-x86.1.0.0-alpha3/bin/klr.host.dll Information : 0 : [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Server.Kestrel in 1ms
System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.loop_size () [0x00000] in <filename unknown>:0
  at Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle.Init (Microsoft.AspNet.Server.Kestrel.Networking.Libuv uv) [0x00000] in <filename unknown>:0
  at Microsoft.AspNet.Server.Kestrel.KestrelThread.ThreadStart (System.Object parameter) [0x00000] in <filename unknown>:0

So I tried this repo, which uses nowin, but after following the instructions I get the following output.
[andrew@nvr helloworldweb]$ k web
/home/andrew/.kre/packages/KRE-mono45-x86.1.0.0-alpha3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DefaultHost]: Project path: /home/andrew/HelloWorldVNext/src/helloworldweb
/home/andrew/.kre/packages/KRE-mono45-x86.1.0.0-alpha3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DefaultHost]: Project root: /home/andrew/HelloWorldVNext
/home/andrew/.kre/packages/KRE-mono45-x86.1.0.0-alpha3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DefaultHost]: Packages path: /home/andrew/.kpm/packages
/home/andrew/.kre/packages/KRE-mono45-x86.1.0.0-alpha3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DependencyWalker]: Walking dependency graph for 'helloworldweb .NETFramework,Version=v4.5'.
/home/andrew/.kre/packages/KRE-mono45-x86.1.0.0-alpha3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [ProjectReferenceDependencyProvider]: helloworldweb 1.0.0, Nowin.vNext 1.0.0
/home/andrew/.kre/packages/KRE-mono45-x86.1.0.0-alpha3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [NuGetDependencyResolver]: Kestrel 1.0.0-alpha4-10294, Microsoft.AspNet.WebSockets.Server 1.0.0-alpha4-10284, Nowin 0.11.0.0, Microsoft.AspNet.Hosting 1.0.0-alpha4-10333, Microsoft.AspNet.Owin 1.0.0-alpha4-10312
/home/andrew/.kre/packages/KRE-mono45-x86.1.0.0-alpha3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [ReferenceAssemblyDependencyResolver]: mscorlib 4.0.0.0, System 4.0.0.0, System.Core 4.0.0.0, Microsoft.CSharp 4.0.0.0
/home/andrew/.kre/packages/KRE-mono45-x86.1.0.0-alpha3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DependencyWalker]: Resolved dependencies for helloworldweb in 72ms
/home/andrew/.kre/packages/KRE-mono45-x86.1.0.0-alpha3/bin/klr.host.dll Information : 0 : [LoaderContainer]: Load name=Microsoft.AspNet.Hosting
System.InvalidOperationException: Unable to load application or execute command 'Microsoft.AspNet.Hosting'. Available commands: web, web-kestrel.
  at Microsoft.Framework.ApplicationHost.Program.ThrowEntryPointNotfoundException (Microsoft.Framework.Runtime.DefaultHost host, System.String applicationName, System.Exception innerException) [0x00000] in <filename unknown>:0
  at Microsoft.Framework.ApplicationHost.Program.ExecuteMain (Microsoft.Framework.Runtime.DefaultHost host, System.String applicationName, System.String[] args) [0x00000] in <filename unknown>:0
  at Microsoft.Framework.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by akoeplinger** [comment]
Kestrel doesn't work on Linux yet.

The issue with Nowin is probably because you're using K 1.0.0-alpha3. It works for me with 1.0.0-alpha4-10353.

**Comment by andrewaggb** [comment]
Where you do get 1.0.0-alpha4-10353?

kvm install 1.0.0-alpha4-10353
Downloading KRE-mono45-x86.1.0.0-alpha4-10353 from https://www.myget.org/F/aspnetmaster/api/v2
KRE-mono45-x86.1.0.0-alpha4-10353 was not found in repository https://www.myget.org/F/aspnetmaster/api/v2

I'm assuming I need to point kvm at a different source?

**Comment by akoeplinger** [comment]
Yes, you need to point kvm to the dev feed, e.g. by setting `KRE_FEED=https://www.myget.org/F/aspnetvnext/api/v2`

**Comment by andrewaggb** [comment]
Yes, that seems to have done it.  the helloworldweb project works after switching to 1.0.0-alpha4-10353 and running kpm restore again.

**Comment by airtonix** [comment]
do you have docker images that make previewing all this a one liner?

**Comment by akoeplinger** [comment]
@airtonix see https://registry.hub.docker.com/u/microsoft/aspnet/
