### ISSUE TITLE
System.InvalidOperationException: Unable to load application or execute command 'Microsoft.AspNet.Hosting'. 

### ISSUE THREAD

**Issue by vnextcoder** [davidfowl/HelloWorldVNext#14]
If i just run the hellowworldweb project on Ubuntu 14.04.2 LTS . 

Docker and KPM and KRE installed , with mono-runtime 

System.InvalidOperationException: Unable to load application or execute command 'Microsoft.AspNet.Hosting'. Available commands: web, web-kestrel.

Below is the error .

azureuser@avinubuntu2:~/HelloWorldVNext/src/helloworldweb$ k web
/home/azureuser/.k/runtimes/kre-mono.1.0.0-beta3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DefaultHost]: Project path: /home/azureuser/HelloWorldVNext/src/helloworldweb
/home/azureuser/.k/runtimes/kre-mono.1.0.0-beta3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DefaultHost]: Project root: /home/azureuser/HelloWorldVNext
/home/azureuser/.k/runtimes/kre-mono.1.0.0-beta3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DefaultHost]: Packages path: /home/azureuser/.k/packages
/home/azureuser/.k/runtimes/kre-mono.1.0.0-beta3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DependencyWalker]: Walking dependency graph for 'helloworldweb Asp.Net,Version=v5.0'.
/home/azureuser/.k/runtimes/kre-mono.1.0.0-beta3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [WalkContext]: Graph walk stage 1 took in 100ms
/home/azureuser/.k/runtimes/kre-mono.1.0.0-beta3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DependencyWalker]: Graph walk took 108ms.
/home/azureuser/.k/runtimes/kre-mono.1.0.0-beta3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [ProjectReferenceDependencyProvider]: helloworldweb 1.0.0, Nowin.vNext 1.0.0
/home/azureuser/.k/runtimes/kre-mono.1.0.0-beta3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [NuGetDependencyResolver]: Kestrel 1.0.0-beta6-11787, Microsoft.AspNet.Hosting 1.0.0-beta6-11923, Microsoft.AspNet.Owin 1.0.0-beta6-11566, Microsoft.AspNet.WebSockets.Server 1.0.0-beta6-11643, Nowin 0.11.0.0
/home/azureuser/.k/runtimes/kre-mono.1.0.0-beta3/bin/Microsoft.Framework.Runtime.dll Information : 0 : Breadcrumbs for servicing will not be written because the breadcrumbs folder () does not exist.
/home/azureuser/.k/runtimes/kre-mono.1.0.0-beta3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [ReferenceAssemblyDependencyResolver]: framework/Microsoft.CSharp 4.0.0.0, framework/mscorlib 4.0.0.0, framework/System 4.0.0.0, framework/System.Core 4.0.0.0
/home/azureuser/.k/runtimes/kre-mono.1.0.0-beta3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [WalkContext]: Populate took 34ms
/home/azureuser/.k/runtimes/kre-mono.1.0.0-beta3/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DependencyWalker]: Resolved dependencies for helloworldweb in 146ms
/home/azureuser/.k/runtimes/kre-mono.1.0.0-beta3/bin/kre.host.dll Information : 0 : [LoaderContainer]: Load name=Microsoft.AspNet.Hosting
System.InvalidOperationException: Unable to load application or execute command 'Microsoft.AspNet.Hosting'. Available commands: web, web-kestrel.
  at Microsoft.Framework.ApplicationHost.Program.ThrowEntryPointNotfoundException (Microsoft.Framework.Runtime.DefaultHost host, System.String applicationName, System.Exception innerException) [0x00000] in <filename unknown>:0
  at Microsoft.Framework.ApplicationHost.Program.ExecuteMain (Microsoft.Framework.Runtime.DefaultHost host, System.String applicationName, System.String[] args) [0x00000] in <filename unknown>:0
  at Microsoft.Framework.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
azureuser@avinubuntu2:~/HelloWorldVNext/src/helloworldweb$

KVM list shows

azureuser@avinubuntu2:~/HelloWorldVNext/src/helloworldweb$ kvm list

Active Version              Runtime Location             Alias

---
-    1.0.0-beta3          mono    ~/.k/runtimes        default

**Comment by davidfowl** [comment]
Update to newer versions of the runtime.
